/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    prizes: Prize;
    codes: Code;
    participants: Participant;
    entries: Entry;
    'prize-claims': PrizeClaim;
    media: Media;
    notifications: Notification;
    'notification-audit': NotificationAudit;
    'otp-verifications': OtpVerification;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    prizes: PrizesSelect<false> | PrizesSelect<true>;
    codes: CodesSelect<false> | CodesSelect<true>;
    participants: ParticipantsSelect<false> | ParticipantsSelect<true>;
    entries: EntriesSelect<false> | EntriesSelect<true>;
    'prize-claims': PrizeClaimsSelect<false> | PrizeClaimsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'notification-audit': NotificationAuditSelect<false> | NotificationAuditSelect<true>;
    'otp-verifications': OtpVerificationsSelect<false> | OtpVerificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'ADMIN' | 'STAFF';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prizes".
 */
export interface Prize {
  id: number;
  name: string;
  quantity: number;
  description?: string | null;
  image?: (number | null) | Media;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codes".
 */
export interface Code {
  id: number;
  serial_code: string;
  is_winner: boolean;
  prize_id?: (number | null) | Prize;
  claimed: boolean;
  claimed_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants".
 */
export interface Participant {
  id: number;
  name: string;
  phone: string;
  verified?: boolean | null;
  verifiedAt?: string | null;
  verificationMethod?: ('otp_whatsapp' | 'sms' | 'manual') | null;
  blocked?: boolean | null;
  blockedReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries".
 */
export interface Entry {
  id: number;
  participant: number | Participant;
  code?: (number | null) | Code;
  result: 'WIN' | 'LOSE' | 'INVALID' | 'ALREADY_USED';
  ip?: string | null;
  user_agent?: string | null;
  request_id?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prize-claims".
 */
export interface PrizeClaim {
  id: number;
  entry: number | Entry;
  participant_name?: string | null;
  participant_phone?: string | null;
  serial_code?: string | null;
  verification_code: string;
  status: 'PENDING' | 'DELIVERED' | 'CANCELLED';
  verified: boolean;
  verified_by?: (number | null) | User;
  verified_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  phone: string;
  template: 'verification' | 'winner-notification' | 'admin-alert';
  payload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  message?: string | null;
  status:
    | 'created'
    | 'queued'
    | 'locked'
    | 'sending'
    | 'provider-accepted'
    | 'sent'
    | 'delivered'
    | 'read'
    | 'retry-scheduled'
    | 'failed'
    | 'dead-letter';
  priority: number;
  attempts: number;
  maxAttempts: number;
  nextAttemptAt?: string | null;
  expiresAt?: string | null;
  lockedAt?: string | null;
  lockedBy?: string | null;
  leaseExpiresAt?: string | null;
  lastError?: string | null;
  sentAt?: string | null;
  deliveredAt?: string | null;
  readAt?: string | null;
  providerMessageId?: string | null;
  providerName?: string | null;
  idempotencyKey?: string | null;
  sendDurationMs?: number | null;
  deliveryPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-audit".
 */
export interface NotificationAudit {
  id: number;
  eventType: 'notification_transition' | 'recovery_bulk' | 'worker_startup';
  notification?: (number | null) | Notification;
  fromStatus?: string | null;
  toStatus?: string | null;
  actor: string;
  error?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  providerResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  durationMs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-verifications".
 */
export interface OtpVerification {
  id: number;
  phone: string;
  code: string;
  expiresAt: string;
  used?: boolean | null;
  usedAt?: string | null;
  lastSentAt: string;
  attempts?: number | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'prizes';
        value: number | Prize;
      } | null)
    | ({
        relationTo: 'codes';
        value: number | Code;
      } | null)
    | ({
        relationTo: 'participants';
        value: number | Participant;
      } | null)
    | ({
        relationTo: 'entries';
        value: number | Entry;
      } | null)
    | ({
        relationTo: 'prize-claims';
        value: number | PrizeClaim;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'notification-audit';
        value: number | NotificationAudit;
      } | null)
    | ({
        relationTo: 'otp-verifications';
        value: number | OtpVerification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prizes_select".
 */
export interface PrizesSelect<T extends boolean = true> {
  name?: T;
  quantity?: T;
  description?: T;
  image?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codes_select".
 */
export interface CodesSelect<T extends boolean = true> {
  serial_code?: T;
  is_winner?: T;
  prize_id?: T;
  claimed?: T;
  claimed_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "participants_select".
 */
export interface ParticipantsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  verified?: T;
  verifiedAt?: T;
  verificationMethod?: T;
  blocked?: T;
  blockedReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries_select".
 */
export interface EntriesSelect<T extends boolean = true> {
  participant?: T;
  code?: T;
  result?: T;
  ip?: T;
  user_agent?: T;
  request_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prize-claims_select".
 */
export interface PrizeClaimsSelect<T extends boolean = true> {
  entry?: T;
  participant_name?: T;
  participant_phone?: T;
  serial_code?: T;
  verification_code?: T;
  status?: T;
  verified?: T;
  verified_by?: T;
  verified_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  phone?: T;
  template?: T;
  payload?: T;
  message?: T;
  status?: T;
  priority?: T;
  attempts?: T;
  maxAttempts?: T;
  nextAttemptAt?: T;
  expiresAt?: T;
  lockedAt?: T;
  lockedBy?: T;
  leaseExpiresAt?: T;
  lastError?: T;
  sentAt?: T;
  deliveredAt?: T;
  readAt?: T;
  providerMessageId?: T;
  providerName?: T;
  idempotencyKey?: T;
  sendDurationMs?: T;
  deliveryPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-audit_select".
 */
export interface NotificationAuditSelect<T extends boolean = true> {
  eventType?: T;
  notification?: T;
  fromStatus?: T;
  toStatus?: T;
  actor?: T;
  error?: T;
  metadata?: T;
  providerResponse?: T;
  durationMs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-verifications_select".
 */
export interface OtpVerificationsSelect<T extends boolean = true> {
  phone?: T;
  code?: T;
  expiresAt?: T;
  used?: T;
  usedAt?: T;
  lastSentAt?: T;
  attempts?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * The phone number where system alerts and winner notifications will be sent. If left empty, it falls back to the WHATSAPP_ADMIN_PHONE environment variable.
   */
  whatsapp_admin_phone?: string | null;
  /**
   * Toggle to enable or disable winner and developer SMTP email alerts to the administrator.
   */
  enable_email_alerts?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  whatsapp_admin_phone?: T;
  enable_email_alerts?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}