import React from 'react';
import { getPayload, type Where } from 'payload';
import config from '@payload-config';
import { ClaimsManager } from './ClaimsManager';
import { getCachedStats } from './cache';

interface CustomListClaimsProps {
  searchParams?: Promise<{
    page?: string;
    search?: string;
    status?: string;
  }>;
}

export async function CustomListClaims({ searchParams }: CustomListClaimsProps) {
  const resolvedParams = (await searchParams) || {};
  const page = Number(resolvedParams.page) || 1;
  const limit = 100;
  const search = resolvedParams.search || '';
  const statusFilter = resolvedParams.status || 'ALL';

  const payload = await getPayload({ config });

  // 1. Trace relations to get matching Entry IDs for search database-side
  let entryIds: (string | number)[] = [];
  if (search) {
    // Find matching participants
    const matchingParticipants = await payload.find({
      collection: 'participants',
      where: {
        or: [
          { name: { like: search } },
          { phone: { like: search } },
        ],
      },
      limit: 100,
    });
    const participantIds = matchingParticipants.docs.map((d) => d.id);

    // Find matching prizes
    const matchingPrizes = await payload.find({
      collection: 'prizes',
      where: {
        name: { like: search },
      },
      limit: 100,
    });
    const prizeIds = matchingPrizes.docs.map((d) => d.id);

    // Find matching serial codes
    let codeIds: (string | number)[] = [];
    if (prizeIds.length > 0) {
      const matchingCodes = await payload.find({
        collection: 'codes',
        where: {
          prize_id: { in: prizeIds },
        },
        limit: 200,
      });
      codeIds = matchingCodes.docs.map((d) => d.id);
    }

    // Now query entries that match participantIds or codeIds
    const orConditions: Where[] = [];
    if (participantIds.length > 0) {
      orConditions.push({ participant: { in: participantIds } });
    }
    if (codeIds.length > 0) {
      orConditions.push({ code: { in: codeIds } });
    }

    if (orConditions.length > 0) {
      const matchingEntries = await payload.find({
        collection: 'entries',
        where: {
          or: orConditions,
        },
        limit: 500,
      });
      entryIds = matchingEntries.docs.map((d) => d.id);
    }
  }

  // 2. Build Query Conditions for Prize Claims
  const where: Where = {};
  if (statusFilter !== 'ALL') {
    where.status = { equals: statusFilter };
  }
  if (search) {
    const orConditions: Where[] = [{ verification_code: { like: search } }];
    if (entryIds.length > 0) {
      orConditions.push({ entry: { in: entryIds } });
    }
    where.or = orConditions;
  }

  // 3. Fetch Paginated Records
  const claimsResult = await payload.find({
    collection: 'prize-claims',
    page,
    limit,
    where,
    depth: 3, // Populate relationships for entry, code, prizes, and participants
    sort: '-createdAt',
  });

  // 4. Cache Statistics (15-second TTL)
  const stats = await getCachedStats('prize-claims-global-stats', 15000, async () => {
    const [total, pending, delivered] = await Promise.all([
      payload.count({ collection: 'prize-claims' }),
      payload.count({
        collection: 'prize-claims',
        where: { status: { equals: 'PENDING' } },
      }),
      payload.count({
        collection: 'prize-claims',
        where: { status: { equals: 'DELIVERED' } },
      }),
    ]);

    return {
      total: total.totalDocs,
      pending: pending.totalDocs,
      delivered: delivered.totalDocs,
    };
  });

  const claims = claimsResult.docs.map((doc) => {
    const entry = doc.entry;

    // Virtual fields are generated by hooks, fallback to manually traversing relationships
    const participantName =
      doc.participant_name ||
      (typeof entry === 'object' && entry?.participant && typeof entry.participant === 'object'
        ? entry.participant.name
        : 'Unknown');
    const participantPhone =
      doc.participant_phone ||
      (typeof entry === 'object' && entry?.participant && typeof entry.participant === 'object'
        ? entry.participant.phone
        : '');
    // Extract prize title
    const prizeName =
      typeof entry === 'object' &&
      entry?.code &&
      typeof entry.code === 'object' &&
      entry.code.prize_id &&
      typeof entry.code.prize_id === 'object'
        ? entry.code.prize_id.name || 'Prize'
        : 'Prize';

    return {
      id: doc.id,
      verificationCode: doc.verification_code,
      status: doc.status as 'PENDING' | 'DELIVERED' | 'CANCELLED',
      verified: Boolean(doc.verified),
      verifiedAt: doc.verified_at || null,
      createdAt: doc.createdAt,
      participantName,
      participantPhone,
      prizeName,
    };
  });

  return (
    <ClaimsManager
      initialClaims={claims}
      currentPage={page}
      totalPages={claimsResult.totalPages}
      totalDocs={claimsResult.totalDocs}
      stats={stats}
      initialSearch={search}
      initialStatus={statusFilter}
    />
  );
}
